tasks:
  - init: corepack enable && corepack prepare pnpm@11.1.1 --activate && pnpm install
    command: pnpm start

ports:
  - name: OWASP Juice Shop
    description: The Juice Shop web server
    port: 3000
    onOpen: open-preview
